### process resume
POST http://localhost:8086/api/v1/screening/process
Content-Type: application/json

{
  "candidate_id": 444,
  "vacancy_id": "1e3f7bd0-5230-49bf-8113-9ec4564a6c08"
}

### create vacancy
POST http://localhost:8086/api/v1/vacancy
Content-Type: application/json

{
  "id": "1e3f7bd0-5230-49bf-8113-9ec4564a6c08",
  "title": "React-разработчик",
  "key_requirements": [
    "React",
    "Javascript",
    "Soft-skills"
  ],
  "questions": [
    {
      "content": "1",
      "reference": "2",
      "time_limit": 30
    },
    {
      "content": "2",
      "reference": "3",
      "time_limit": 45
    }
  ]
}

