### process resume
POST http://localhost:8086/api/v1/screening/process
Content-Type: application/json

{
  "candidate_id": 200,
  "vacancy_id": "a8f53744-80f3-4ced-9d1f-4b99d74387c9"
}

### create vacancy
POST http://localhost:8086/api/v1/vacancy
Content-Type: application/json

{
  "id": "1e3f7bd0-5230-49bf-8113-9ec4464a6c08",
  "title": "kek",
  "key_requirements": [
    "rot_",
    "ipal"
  ],
  "questions": [
    {
      "content": "1",
      "reference": "2",
      "time_limit": 30
    },
    {
      "content": "2",
      "reference": "3",
      "time_limit": 45
    }
  ]
}

