services:
  hr-helper:
    container_name: hr-helper
    build: .
    env_file: prod.env
    restart: on-failure
    depends_on:
      - tika
    ports:
      - "8086:8086"

  tika:
    image: apache/tika:latest
    restart: on-failure
